# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "feat/init" ]
  pull_request:
    branches: [ "feat/init" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: '11'
        # sbt-version: '1.4.7'
    - name: Install Apache Spark
      run: |
          wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
          tar xvf spark-3.1.2-bin-hadoop3.2.tgz
          sudo mv spark-3.1.2-bin-hadoop3.2 /opt/spark
          export SPARK_HOME=/opt/spark
          export PATH=$SPARK_HOME/bin:$PATH
  
    - name: Verify Spark Installation
      run: |
          /opt/spark/bin/spark-shell --version 
    - name: Install dependencies
      run: sbt update
    - name: Run tests
      run: sbt test
    - name: Upload JSON output
      uses: actions/upload-artifact@v2
      with:
        name: spark-output
        path: target/output/**/*.json

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false
  
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/output/**/*.json
          asset_name: spark-output-${{ github.sha }}.json
          asset_content_type: application/json