# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: [ "feat/init" ]
  pull_request:
    branches: [ "feat/init" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: '11'
        # sbt-version: '1.4.7'
    - name: Install Apache Spark
      run: |
          wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
          tar xvf spark-3.1.2-bin-hadoop3.2.tgz
          sudo mv spark-3.1.2-bin-hadoop3.2 /opt/spark
          export SPARK_HOME=/opt/spark
          export PATH=$SPARK_HOME/bin:$PATH
  
    - name: Verify Spark Installation
      run: |
          /opt/spark/bin/spark-shell --version 
    - name: Install dependencies
      run: sbt update
    - name: Run tests
      run: sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    # - name: Upload dependency graph
    #   uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
